# Generated by Django 4.2.8 on 2023-12-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscribe_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users_images/default.png', upload_to='users_images/'),
        ),
    ]
