# Generated by Django 4.2.8 on 2023-12-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_subscribe_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'MALE')], default='F', max_length=1, null=True),
        ),
    ]
