# Generated by Django 4.2.8 on 2023-12-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
