# Generated by Django 4.2.8 on 2023-12-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_review_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
