# Generated by Django 3.2 on 2023-12-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20231203_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrycity',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='countrycity',
            old_name='country_id',
            new_name='country',
        ),
        migrations.AlterUniqueTogether(
            name='countrycity',
            unique_together={('country', 'city')},
        ),
    ]
