# Generated by Django 3.2 on 2023-11-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231118_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategorySex',
            new_name='CategoryGender',
        ),
        migrations.RenameModel(
            old_name='Sex',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='categorygender',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='categorygender',
            old_name='sex_id',
            new_name='sex',
        ),
    ]
