# Generated by Django 3.2 on 2023-11-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20231118_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorygender',
            old_name='sex',
            new_name='gender',
        ),
    ]
