# Generated by Django 3.2 on 2023-11-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_sex_categorygender_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorygender',
            unique_together={('category', 'gender')},
        ),
    ]
