# Generated by Django 4.2.8 on 2023-12-19 23:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0030_alter_product_date_create'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Creation Date')),
                ('product_size_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsizecolor', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'product_size_color')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Last Updated')),
                ('created', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Created At')),
                ('first_name', models.CharField(max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=128, verbose_name='Email')),
                ('mobile_phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 11 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile Phone')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=6, verbose_name='Postal Code')),
                ('cart', models.JSONField(verbose_name='Cart')),
                ('country_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.countrycity', verbose_name='Country & City')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Payment Type',
                'verbose_name_plural': 'Payment Types',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('baseproductlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.baseproductlist')),
                ('quantity', models.PositiveIntegerField(verbose_name='Product Quantity')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
            bases=('orders.baseproductlist',),
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('baseproductlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.baseproductlist')),
            ],
            options={
                'verbose_name': 'Favourite',
                'verbose_name_plural': 'Favourites',
            },
            bases=('orders.baseproductlist',),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.paymenttype', verbose_name='Payment Type'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.status', verbose_name='Order Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
    ]
