# Generated by Django 3.2 on 2023-12-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paymenttype_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'verbose_name': 'Payment Types'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Statuses'},
        ),
    ]
