# Generated by Django 4.2.8 on 2023-12-16 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_delete_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_auto_20231203_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Creation Date')),
                ('product_size_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productsizecolor', verbose_name='Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('baseproductlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.baseproductlist')),
                ('quantity', models.PositiveIntegerField(verbose_name='Product Quantity')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
            bases=('orders.baseproductlist',),
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('baseproductlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.baseproductlist')),
            ],
            options={
                'verbose_name': 'Favourite',
                'verbose_name_plural': 'Favourites',
            },
            bases=('orders.baseproductlist',),
        ),
    ]
