# Generated by Django 4.2.8 on 2023-12-16 21:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0029_delete_cart'),
        ('orders', '0006_baseproductlist_cart_favourites'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baseproductlist',
            unique_together={('user', 'product_size_color')},
        ),
    ]
