# Generated by Django 3.2 on 2023-11-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_categorygender_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductCategoryGender',
        ),
        migrations.RenameField(
            model_name='productcategorygender',
            old_name='category_sex_id',
            new_name='category_gender',
        ),
        migrations.RenameField(
            model_name='productcategorygender',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productsizecolor',
            old_name='color_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='productsizecolor',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productsizecolor',
            old_name='size_id',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='productsizecolorcount',
            old_name='product_size_color_id',
            new_name='product_size_color',
        ),
        migrations.AlterUniqueTogether(
            name='productcategorygender',
            unique_together={('product', 'category_gender')},
        ),
        migrations.AlterUniqueTogether(
            name='productsizecolor',
            unique_together={('product', 'size', 'color')},
        ),
    ]
