# Generated by Django 3.2 on 2023-12-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='categorygender',
            options={'verbose_name': 'Categories and Genders'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name': 'Genders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Products Images'},
        ),
        migrations.AlterModelOptions(
            name='productsizecolor',
            options={'verbose_name': 'Products & Sizes & Colors'},
        ),
        migrations.AlterModelOptions(
            name='productsizecolorcount',
            options={'verbose_name': 'Products & Sizes & Colors & Counts'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Sizes'},
        ),
        migrations.AddField(
            model_name='product',
            name='category_gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.categorygender'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductCategoryGender',
        ),
    ]
