# Generated by Django 3.2 on 2023-12-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20231203_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_gender',
        ),
        migrations.AddField(
            model_name='product',
            name='category_gender',
            field=models.ManyToManyField(to='products.CategoryGender'),
        ),
    ]
