# Generated by Django 3.2 on 2023-12-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20231203_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Images',
            },
        ),
        migrations.CreateModel(
            name='SizeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size')),
            ],
            options={
                'verbose_name': 'Sizes & Colors',
                'unique_together': {('size', 'color')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='productsizecolor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productsizecolor',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productsizecolor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsizecolor',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productsizecolorcount',
            name='product_size_color',
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductSizeColor',
        ),
        migrations.DeleteModel(
            name='ProductSizeColorCount',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='products.Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_color',
            field=models.ManyToManyField(to='products.SizeColor'),
        ),
    ]
