# Generated by Django 3.2 on 2023-12-03 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20231203_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.AddField(
            model_name='categorygender',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='count of product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_information',
            field=models.TextField(blank=True, null=True, verbose_name='additional information'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_gender',
            field=models.ManyToManyField(to='products.CategoryGender', verbose_name='category and gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, null=True, verbose_name='long description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_color',
            field=models.ManyToManyField(to='products.SizeColor', verbose_name='size and color'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='default',
            field=models.BooleanField(default=False, verbose_name='is_default_photo'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product'),
        ),
    ]
