# Generated by Django 3.2 on 2023-12-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20231203_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorygender',
            name='count',
        ),
        migrations.AddField(
            model_name='sizecolor',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='count of product'),
            preserve_default=False,
        ),
    ]
