# Generated by Django 3.2 on 2023-12-03 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20231203_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_color',
        ),
        migrations.CreateModel(
            name='SizeColorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='count of product')),
                ('size_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sizecolor')),
            ],
            options={
                'verbose_name': 'Size & Color & Count',
                'verbose_name_plural': 'Sizes & Colors & Counts',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='size_color_counts',
            field=models.ManyToManyField(to='products.SizeColorCount', verbose_name='Size| Color| Count'),
        ),
    ]
