# Generated by Django 3.2 on 2023-12-03 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20231203_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='count of product')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color', verbose_name='color')),
            ],
            options={
                'verbose_name': 'Size & Color',
                'verbose_name_plural': 'Sizes & Colors',
            },
        ),
        migrations.RemoveField(
            model_name='sizecolorcount',
            name='size_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_color_counts',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='product'),
        ),
        migrations.DeleteModel(
            name='SizeColor',
        ),
        migrations.DeleteModel(
            name='SizeColorCount',
        ),
        migrations.AddField(
            model_name='productsizecolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='productsizecolor',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size_colors', to='products.size', verbose_name='size'),
        ),
        migrations.AlterUniqueTogether(
            name='productsizecolor',
            unique_together={('size', 'color', 'product')},
        ),
    ]
