# Generated by Django 4.2.8 on 2023-12-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_productcategorygender_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='default',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='img/default-product.png', upload_to='product_images/', verbose_name='image'),
        ),
    ]
