# Generated by Django 4.2.8 on 2023-12-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_productimage_default_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsizecolor',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='products.size', verbose_name='size'),
        ),
    ]
