# Generated by Django 4.2.8 on 2023-12-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='static/categories_images/default.jpeg', upload_to='categories_images/'),
        ),
    ]
