# Generated by Django 4.2.8 on 2023-12-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_product_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='date_create',
        ),
    ]
