# Generated by Django 4.2.8 on 2023-12-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_rename_date_product_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='product_images/default.jpg', upload_to='product_images/', verbose_name='image'),
        ),
    ]
