# Generated by Django 4.2.8 on 2023-12-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_create',
            field=models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Creation Date'),
        ),
    ]
